version: "3.8"

services:
  frontend:
    image: frontend
    ports:
      - "5000:5000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    container_name: frontend

  backend:
    image: backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REQUEST_ORIGIN: http://localhost:5000
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    container_name: backend

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data/

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
